### ISSUE TITLE
Custom Dates panel

### ISSUE THREAD

**Issue by Shawnfoto** [shahabyazdi/react-multi-date-picker#11]
Hi Shahab,

May I ask that can I add other event on dates panel?
For example, click certain date, it will do something.

**Comment by shahabyazdi** [comment]
I recently released DatePanel as a plugin.
Do you just need onClickListenre? or you want more features?
Please just tell me , I will add that possibility for you.

**Comment by Shawnfoto** [comment]
Because when I click date, it will direct to specific date.
Now I would like to click blue block of date and it will be removed.
![螢幕快照 2021-01-06 下午10 40 47](https://user-images.githubusercontent.com/18244561/103781190-f9a79200-5070-11eb-812a-9c28c2381640.png)

**Comment by shahabyazdi** [comment]
I will add a property called onClickDate to the DatePanel plugin, then you can define a listener for it, when you click on any of the dates that listener will run and give you the date clicked, then you can filter that specific date.

**Comment by Shawnfoto** [comment]
Thank you so much.

**Comment by shahabyazdi** [comment]
You're welcome, I'm working on it😉

**Comment by shahabyazdi** [comment]
I think [this ](https://codesandbox.io/s/date-panel-click-listener-m40nh)is what you wanted.

**Comment by Shawnfoto** [comment]
> I think [this ](https://codesandbox.io/s/date-panel-click-listener-m40nh)is what you wanted.

Cool, it is, thank you.
But "x" still can remain there.

**Comment by shahabyazdi** [comment]
that is an optional feature.
You can easily return the x button by setting the removeButton prop to true , or you can delete that line.

**Comment by Shawnfoto** [comment]
```
console.log(value)
```
It seems the array of dates didn't sorting.

**Comment by shahabyazdi** [comment]
In early versions, datepicker sorted the selected dates by default. But I noticed that sorting dates confuses the amount of dates selected by the user.
For example, if you want to prioritize user-selected dates, sorting the dates will make it impossible for you.
That's why I eliminated this possibility. But if you want the dates to be displayed in order, you can easily sort them like this :
```javascript
setValue(value.sort((a, b) => a - b))
```

I will update [the previous codesandbox](https://codesandbox.io/s/date-panel-click-listener-m40nh?file=/src/App.js) for you to see the result.

**Comment by shahabyazdi** [comment]
Ok, [I added a prop](https://shahabyazdi.github.io/react-multi-date-picker/#multiple-mode-#3) for sorting selected dates.
