### ISSUE TITLE
Multi Date Functionality Display Issues in Latest version.

### ISSUE THREAD

**Issue by nishStoryDigital** [shahabyazdi/react-multi-date-picker#12]
Hi Shahab, I've upgraded to the latest version ( 2.0.2 ) from 1.8.0. Here are my observations while using this package for our project.

1. It would be better if multiple dates selected can be displayed in ascending order in the date field.
2. If I use, a custom component, like MUI-Textfield as the input field, and select multiple dates, selected dates doesn't show in the field, but their value is being correctly taken.

Feel free to experiment in this [Sandbox](https://codesandbox.io/s/interesting-river-8wc5t?file=/package.json).

![custom-tf](https://user-images.githubusercontent.com/73821978/103889864-1beeed80-510d-11eb-8206-92812b8edeee.png)
![date-order](https://user-images.githubusercontent.com/73821978/103889870-1db8b100-510d-11eb-9f60-c6f4fc38d041.png)

**Comment by shahabyazdi** [comment]
Firstly, the reason I told you to upgrade the package was because two persons in same date told me that they had problem with their  packages and I thought it is better to tell you so the possible problem could be prevented. But after doing several tests in previous versions I noticed that there is no problem in previous packages and you can downgrade the package to v1.8.0 safely. 

Regarding the sorting dates : based on reasons which I mentioned in #11 I'm not gonna sort dates anymore.  you should sort them manually in onChane method 
```javascript
onChange(dates=>setValue(dates.sort((a,b)=>a-b)))
```

and in regard to setting string date in custom inputs at multiple and range mode , I changed the stringDate to array of strings in order to make it more feasible to work with, for example maybe you want to display just first and second dates or you want to use different seperetor instead "," which is in default input , only you can do this things if you have got array of strings and it's not possible to do such works with stringDate , you can see the example [here](https://shahabyazdi.github.io/react-multi-date-picker/#multiple-&-range)

**Comment by shahabyazdi** [comment]
also I modified your codesandbox to work as you want. 

https://codesandbox.io/s/young-framework-lk852?file=/src/MultiDatePicker.js

**Comment by shahabyazdi** [comment]
fb908dce2d0477db50b36fd9e43fd216c84ba6fd
