### ISSUE TITLE
Formatting issue when setting new value

### ISSUE THREAD

**Issue by nishStoryDigital** [shahabyazdi/react-multi-date-picker#2]
I'm using Fullcalendar alongside your date picker.  Here is my code

`const [selectedDate, setSelectedDate] = useState(moment().toDate());`

```
<DatePicker
        value={selectedDate}
        multiple={repeat}
        format='DD MMM YYYY'
        minDate={moment().toDate()}
        maxDate={moment().add(7, 'd').toDate()}
        style={styles.textfield}
        onChange={date => console.log(new Date(date[0]))}
 />
```

When I handle date click event in fullcalendar, and set new date, it fails. The error statement being...

**TypeError: r.format is not a function**

```
const handleDateEvent = (event) => {
        // event.date gives Sat Nov 28 2020 19:00:00 GMT+0530 (India Standard Time)
        const selDate = moment(event.date).valueOf()  
        setSelectedDate(selDate);  // throws error
};
```

However, if I do it like this, it sorta works, but renders unwanted date format as in " 2020-11-25T21:00:00+05:30 ", even though I have specified the format already. 

```
 const handleDateEvent = (event) => {
        setSelectedDate(moment(event.date));
 };
```

**Comment by shahabyazdi** [comment]
as I see the code you wrote , there is no need for using moment in DatePicker. Although it's ok if you want to use it .
in onChange you don't get date . you get instanceof [DateObject ](https://github.com/shahabyazdi/react-date-object) and you can convert it to js date or other supported calendars (gregorian, persian, arabic,indian). for converting dateObject to js date; use dateObject.toDate().

please try this and let me know the result.

const [selectedDate, setSelectedDate] = useState(moment().toDate());

<DatePicker
        value={selectedDate}
        multiple={repeat}
        format='DD MMM YYYY'
        minDate={moment().toDate()}
        maxDate={moment().add(7, 'd').toDate()}
        style={styles.textfield}
        onChange={dateObject => {
             console.log("js date:", dateObject.toDate())
             console.log(dateObject.format("DD MMM YYYY"))
             console.log(moment(dateObject.toDate()).valueOf(), dateObject.valueOf())
             setSelectedDate(dateObject.toDate()) //I recommend you not to convert given dateObject toDate() in order to avoid unnecessary process
        }}
 />

**Comment by nishStoryDigital** [comment]
Thanks for the suggestion, it did help me out. I have attached  a [Code Sandbox Link](https://codesandbox.io/s/wispy-river-m3nji?file=/src/CalComp.js
) to show my implementation of the same and have also raised queries in the comments.

 Feel free to experiment with the same and let me know when I could have made any mistakes. 

Many thanks.

**Comment by shahabyazdi** [comment]
I took a look at your code and realized where the problem is, I'm working on that, hope to make it until tomorrow

**Comment by shahabyazdi** [comment]
I made some changes to datepicker and [published it on npm](https://www.npmjs.com/package/react-multi-date-picker/v/1.7.1), hope it would be helpful and solve the problem.
also I forked your codesandbox [here ](https://codesandbox.io/s/distracted-hopper-31666?file=/src/MultiDatePicker.js)so that you can see the result without updating your package dependency . please check it and let me know if there is still any problem
**about your losing required format issue when you enable minDate Prop : the date you set in datepicker as value must be in range of min and max date (bigger than min date and smaller than max date ) otherwise datepicker recognise it as invalid date and doesn't format it.

**Comment by nishStoryDigital** [comment]
Hi Shahab, Appreciate your efforts to improve this package, however , the issue is still persistent for my case. If the height of the content ( in this case, the bottomsheet ) is less than the height of the calendar, the calendar appears as cropped out of the container as seen in this [sandbox](https://codesandbox.io/s/elegant-brattain-7lrnb?file=/src/CalComp.js) .

Please let me know if it is feasible or not, else I would have to modify the UI to adjust the height of the calendar.

Many thanks

**Comment by shahabyazdi** [comment]
First of all, I have to apologize to you that this problem lasted so long and took your time.

The reason why the stringDate is "" at the first moment is that we set the pickerDate to null in useState ```const [pickerDate, setPickerDate] = useState(null)```, and because of that , the stringDate becomes empty.

Regarding the calendar position I came to the conclusion that I should add a prop so than the user can manually adjust the calendar position . for example (top-left bottom-left top-center ,...)
I hope this can solve your problem

here is the [codesandbox](https://codesandbox.io/s/datepicker-test-hinm8?file=/src/MultiDatePicker.js)

Again, I apologize for this problem taking so long

**Comment by nishStoryDigital** [comment]
Hi Shahab,

No need for apologies, its all cool. 😃

I see both the issues being resolved now and I thank you very much for your efforts to resolve these issues asap.

Please do update your readme by adding the `calendarPosition` property to the list.

**Comment by shahabyazdi** [comment]
You're welcome
It's good to hear that🙂
