### ISSUE TITLE
The date panel does not update when using both a minimum selection date and mobile mode

### ISSUE THREAD

**Issue by davidchoy** [shahabyazdi/react-multi-date-picker#20]
Issue: The date panel does not update when using both a minimum selection date and mobile mode.

To reproduce the problem, please see:
https://codesandbox.io/s/datepanel-broken-with-mindate-when-ismobile-3i0cp?file=/src/App.js

I took a cursory look at the code and couldn't figure out how to fix this problem. Can you help or point me in a good direction?

```
<DatePicker
  value={bookingDates}
  onChange={(dateObjects) => {
    setBookingDates(dateObjects);
  }}
  multiple={true}
  plugins={[<DatePanel />]}
  className="rmdp-mobile" // Remove either this line (className="rmdp-mobile") or the next to fix the DatePanel
  minDate={today} // Remove either this line (minDate={today}) or the next to fix the DatePanel
/>
```

**Comment by shahabyazdi** [comment]
I will work on it and let you know about it.

**Comment by shahabyazdi** [comment]
Hello
The problem you mentioned occurred because in mobile mode, the user-selected dates were stored as a temporary date in a ref.

Storing dates in the ref did not update the calendar, causing this problem.
In version 2.2.1, temporary dates are also stored in the state to avoid this problem.

I hope your problem has been resolved with the changes I made.

**Comment by shahabyazdi** [comment]
I also fixed the runkit problem you mentioned in issue #19 at version 2.2.5.

**Comment by shahabyazdi** [comment]
I'm closing this issue. Please let me know if your problem persists.
