### ISSUE TITLE
Trying to make a custom plugin that takes two timepickers, one for each month but not sure how to propagate the updates.

### ISSUE THREAD

**Issue by adventofryz** [shahabyazdi/react-multi-date-picker#210]
![image](https://github.com/shahabyazdi/react-multi-date-picker/assets/22504701/eeee5d54-0e26-4857-a084-581027c6a523)

Posted image to illustrate what I am trying to do.

![image](https://github.com/shahabyazdi/react-multi-date-picker/assets/22504701/9a718ec7-4ba7-4a3c-ac90-89e2ae0aa0d8)
This is the custom plugin I had made for timepickers.

![image](https://github.com/shahabyazdi/react-multi-date-picker/assets/22504701/c10fcf67-f757-4db0-a51f-0cdff8ebe305)
This is the datepicker component.

Could I get some direction on how to proceed. I tried to look into your code for the time picker but I did not understand how to update the selected date with each individual time without using focusing.

**Comment by adventofryz** [comment]
I managed to get them to focus separately by manipulating the state using focused: state.selectedDate[0] for startDate and focused: focused: state.selectedDate[1] for end date.
But it doesn't update the actual input values.

**Comment by shahabyazdi** [comment]
Hello there!

In order to update the input value, you'll need to perform a rerender. Simply mutating the selected date won't trigger a rerender. Instead, you should set the internal state with the updated value. Here's an example:

```javascript
handleChange(selectedDate, {
   ...state,
   selectedDate,
});
```

You can obtain the handleChange method from the props of your custom plugin.

**Comment by adventofryz** [comment]
Hello! Thanks for the assistance!

1. I tried doing what you suggested but my popup keeps closing. How do I keep it open like the date panel example?

![image](https://github.com/shahabyazdi/react-multi-date-picker/assets/22504701/740cece5-5d64-4ddc-b15b-5ec1b8c789e3)

![image](https://github.com/shahabyazdi/react-multi-date-picker/assets/22504701/0cdcb25f-5f02-4600-b03b-a1a45d1b94ea)

2. Second issue I have is, whenever I change start date and end date the timepickers get reset. Is there a way to keep the timepickers without resetting? 
3. Another issue is at start when the picker is empty. I increase the time for one picker and the other picker also increases. Is there a way to keep it unique and only bounded by start date and end date.

**Comment by adventofryz** [comment]
I have a codesandbox I am working in which shows what I have so far.
https://codesandbox.io/s/serverless-surf-znsg8x?file=/src/App.js

**Comment by shahabyazdi** [comment]
1. The reason the popup is closed is that the plugins are declared within the app component, and they get regenerated every time the app component is re-rendered.

2. I have created a function called "update" that updates the hour and minute of the state's date, forcing it to update with the focused date's hour and minute. It seems to be working now.

3. For the third issue, I believe we should prevent the user from updating the time when no date is selected. If we don't prevent the user from updating the time, considering that only one date is available in the calendar state, both time pickers will be updated because they are connected to the state's date. Alternatively, we could create a custom time picker that is connected to the internal state.

I have forked your example, and now your time selector is functioning properly.
https://codesandbox.io/s/wonderful-orla-yg7tzv?file=/src/App.js

**Comment by adventofryz** [comment]
Thanks for the assistance again. The library offers a lot of flexibility that other libraries don't have. Great work.

**Comment by adventofryz** [comment]
Hello! I had to reopen the case as I have a few more little issues.

1. First issue is with the time pickers swapping their chosen times or breaking them when typing in the input field itself. This happens if you selected the same date twice and just change the times. I chose 20-6-2023 11:40 to 20-6-2023 11:40 and then just changed the times directly from input field to some values but the timepicker is reflecting incorrect times. 

   I am not sure if I am doing the focusing correctly as with _startProps_ and _endProps_ passed to the individual timepickers.

   ![image](https://github.com/shahabyazdi/react-multi-date-picker/assets/22504701/d2592721-437e-4013-869b-8ba5d596d458)

2. I have added the completed Preset functionality so users can choose time ranges quicker but am not sure if this is a correct implementation. I noticed so much flickering in the input field itself whenever I clicked on the selections.

3. Is there a way to insert the timepickers directly below the calendars instead of method I did where I hid the border bottom and just placed the pickers there? I checked the rmdp class structure and couldn't find a way to insert it directly after the rmdp-day-picker class.

Any assistance would be greatly appreciated.

Updated sandbox: https://codesandbox.io/s/amazing-hofstadter-5z245j?file=/src/App.js

**Comment by shahabyazdi** [comment]
1. I'm not sure why this issue is occurring either. I will need to review the source code to identify the bug. However, I have managed to temporarily resolve the problem using a function called "findValidDate!"

2. Unfortunately, I couldn't identify any issues with the input field.

3. I have applied a fixed width to the presets component using the "presets" class name. Additionally, I have added the same margin-left value to the custom timepicker wrapper using the "custom-margin" class.

https://codesandbox.io/s/priceless-satoshi-vszk37?file=/src/styles.css:483-496

**Comment by adventofryz** [comment]
Thanks for the assist! If you are planning to make this an actual example on the site it would be great as many enterprise based datepickers could benefit from this preset plus timepicker based on start and end date functionality. 
Since this has popper added to it, that's a great incentive to use as well.
