### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by Nippondanso** [shahabyazdi/react-multi-date-picker#29]
how i can handle "changeMonth" event?
![image](https://user-images.githubusercontent.com/28148918/113300525-adce5700-9306-11eb-869b-99b8a273f99c.png)
![image](https://user-images.githubusercontent.com/28148918/113300637-c8083500-9306-11eb-8462-faeb12845f5b.png)
i want to know what month is current?

**Comment by shahabyazdi** [comment]
Hi
I apologize for the delay in replying.
I wanted to include the same mapِDays feature for months and years, so that months and years could be personalized in the same way of days, but I could not come to a good conclusion, so I dropped it.
There are two ways to handle "changeMonth" events;
You either want to define a click listener on months, or want to define a listener to change the months. There is a small difference between these two, which is further highlighted by looking at this image:

![months](https://user-images.githubusercontent.com/18695593/113389948-b7c37a80-9345-11eb-940d-7f9b708def65.jpg)

Given that clicking the back and forward buttons may also change the amount the month, so I want you to tell me that which listeners you prefer ? a click listener or change listener ?

**Comment by shahabyazdi** [comment]
onMonthChange was added in version 2.6.0.

```javascript
<DatePicker
   onMonthChange={date=> console.log(date.format())}
/>
```
There is also an example of it on the [demo page](https://shahabyazdi.github.io/react-multi-date-picker/events/#onmonthchange).
