### ISSUE TITLE
Date picker should be opened always

### ISSUE THREAD

**Issue by vivekkbaskaran** [shahabyazdi/react-multi-date-picker#3]
I need a date picker without having the input type or icon. it should always open. Please help me on this

**Comment by shahabyazdi** [comment]
Given that the position of the calendar in datepicker is absolute, it doesn't seem to work for your case, since the calendar covers other below elements.

In your case , it would be better to use an input along with calendar instead of datepicker.

Please take a look at this [example ](https://codesandbox.io/s/input-calendar-jjkoh?file=/src/App.js)and let me know if it works or not.

**Comment by vivekkbaskaran** [comment]
@shahabyazdi  Thanks a lot Man :-)

**Comment by shahabyazdi** [comment]
you're welcome 🙂
