### ISSUE TITLE
can i change the order of days?

### ISSUE THREAD

**Issue by Nippondanso** [shahabyazdi/react-multi-date-picker#35]
now calendar has order like this: Su, Mo, Tu, We, Th, Fr, Sa

can i change order to :  Mo, Tu, We, Th, Fr, Sa, Su

**Comment by shahabyazdi** [comment]
Please install v2.5.4 and use `weekStartDayIndex` prop to set the first day of week. 

If you see any typescript errors, completely uninstall and install the package again. 
```
npm uninstall react-multi-date-picker
npm install --s react-multi-date-picker@2.5.4
```
Because I tested it in typescript and it works

Example : https://shahabyazdi.github.io/react-multi-date-picker/other-examples/#changing-start-day-of-the-week

**Comment by Nippondanso** [comment]
it works perfectly! Thank you very much!

**Comment by shahabyazdi** [comment]
You're welcome ☺️
