### ISSUE TITLE
isSameDate only works with DateObject() but not a native Date()

### ISSUE THREAD

**Issue by WebDev-Akhil** [shahabyazdi/react-multi-date-picker#49]
isSameDate method can be used to compare 2 dates and do something based on that, but it only works when compared to a `DateObject()` and not a `Date() `

Example - 

```js
if (isSameDate(date, new DateObject())) props.style.color = "green";
// this turns today's date in calendar to green color

if (isSameDate(date, new Date())) props.style.color = "green";
// this also should do  the same job but it doesn't

```

link to [codesand box](https://codesandbox.io/s/react-multi-date-picker-forked-v85sc)

**Comment by WebDev-Akhil** [comment]
Possible Solution - A helper function which converts a new Date() to new DateObject()

```js
const newFunction (Arg1) => {
//converts Arg1 to DateObject()
// returns DateObject()
}
.
.
const legacyDate = new Date()
.
.
if (isSameDate(date, newFunction(legacyDate))) props.style.color = "green";
```

**Comment by shahabyazdi** [comment]
Hello

Thank you very much for your useful comment.

Comparing JavaScript Date and DateObject is only possible if we want to compare both in the Gregorian Calendar.

Converting a Javascript Date to a DateObject is very easy, just put that date in the DateObject constructor, and it's done!. So the helper function you suggested can be written like this:

```javascript

function toDateObject(jsDate){
   return new DateObject(jsDate)
}

```

Also, if we want to convert the Javascript Date to other calendars (Solar Hijri, Lunar Hijri, Indian, ...) and then compare them with each other, we have to get the second argument called `calendar` in our helper function, so in general, our helper function becomes like this:

```javascript

function toDateObject(jsDate, calendar){
   return new DateObject({ date:jsDate, calendar })
}

```
Incidentally, a [similar function](https://github.com/shahabyazdi/react-multi-date-picker/blob/4f7723cf37bb8b3675ba51834c90e3aff00a25bd/src/components/calendar/calendar.js#L487) is currently available in the package, So I will export it in the next version.

___
P.S

Because mapDays runs one time per each day (at least 35 times per one render), perform heavy operations outside of mapDays as much as possible.

For example, if you need to compare a specific date in mapDays, it is best to set that date outside of mapDays, and only compare it inside the mapDays. This will prevent the date to generate 35 times in each render.

```javascript
const jsDate = new Date()

function mapDays({date}){
   if(new Date().getFullYear()===date.year) //bad

   if(jsDate.getFullYear()===date.year) //good
}

````

**Comment by WebDev-Akhil** [comment]
Hi. 

Thanks, this one was solved for me, after using the helper function to convert new Date() to DateObject.

**Comment by WebDev-Akhil** [comment]
I still have one weird issue. 

Whenever I try to set select some date in the dateTimePicker, I get an error in the console saying `"Unhandled Promise Rejection: Error: Expected value to be a date"`

And, this only happens when I use `react-multi-date-picker`. I tried using some other date picker available in npm directory and I don't get that error. (Note - backend code is completely the same in both cases. i.e. Onchange function takes the date and updates at some place on the website)

<img width="1344" alt="Screenshot 2021-06-24 at 22 21 47" src="https://user-images.githubusercontent.com/25116883/123334726-6b01d100-d53b-11eb-95ca-71dee019e270.png">
