### ISSUE TITLE
How to set mask for input?

### ISSUE THREAD

**Issue by AliBayatMokhtari** [shahabyazdi/react-multi-date-picker#54]
I wanna mask the input to set date or time. for example for date: ----/--/-- and for time: --:--

**Comment by shahabyazdi** [comment]
You can render an input with the ability to mask for your date picker:

https://codesandbox.io/s/gallant-butterfly-2mzlf?file=/src/App.js

**Comment by AliBayatMokhtari** [comment]
> You can render an input with the ability to mask for your date picker:
> 
> https://codesandbox.io/s/gallant-butterfly-2mzlf?file=/src/App.js

I am using Material ui Filled Input component and when i am using this third party library for masking input it destroys the filled variant styles of material ui FilledInput.

**Comment by shahabyazdi** [comment]
I forked [this example](https://material-ui.com/components/text-fields/#integration-with-3rd-party-input-libraries) from the Material UI documentation so that its input can be rendered in the DatePicker.
Please see it and let me know if you have any problems.

**Material demo (forked):**
https://codesandbox.io/s/material-demo-forked-k9xin?file=/demo.js

**Comment by AliBayatMokhtari** [comment]
> I forked [this example](https://material-ui.com/components/text-fields/#integration-with-3rd-party-input-libraries) from the Material UI documentation so that its input can be rendered in the DatePicker.
> Please see it and let me know if you have any problems.
> 
> **Material demo (forked):**
> https://codesandbox.io/s/material-demo-forked-k9xin?file=/demo.js

Thanks. it works great ✅

**Comment by shahabyazdi** [comment]
You're welcome.
