### ISSUE TITLE
How do I make <Calendar/> become responsive?

### ISSUE THREAD

**Issue by mie035** [shahabyazdi/react-multi-date-picker#55]
I want to display "Calendar" component to fill the screen that is shown.
Is there any way to realize this with egitimate measure using the api?

**Comment by shahabyazdi** [comment]
I do not think the result would be very perfect, but you can wrap the calendar in a div and after importing the CSS file of [this example](https://codesandbox.io/s/confident-booth-k4dtm?file=/src/styles.css), by changing the length and width of the wrapper, the length and width of the calendar will also change.

**Comment by mie035** [comment]
I couldn't think of that idea =o
that is very what I need!
Thank you. I've learned a lot from your code and words.

**Comment by shahabyazdi** [comment]
You're welcome.

**Comment by rmelara-designli** [comment]
Thank you @shahabyazdi  your example was really useful
I just want to add that in my case I was loosing the styles everytime the page reloading

so I added !important to my style in order to not lose the style when realoading the page 

.custom-calendar .rmdp-top-class,
.custom-calendar .rmdp-calendar > div:not(:first-child),
.custom-calendar .rmdp-day-picker {
  height: 100% !important;
}

.custom-calendar,
.custom-calendar .rmdp-calendar,
.custom-calendar .rmdp-day-picker > div {
  width: 100% !important;
  height: 100% !important;
}

.custom-calendar .rmdp-day {
  width: unset !important;
  height: 100% !important;
  flex: 1 !important;
}

.custom-calendar .rmdp-week {
  height: 14.5% !important;
}
