### ISSUE TITLE
[Feature Suggestion] Expose the raw event for onChange

### ISSUE THREAD

**Issue by henry132109** [shahabyazdi/react-multi-date-picker#61]
We're writing a scheduling system in which there can be a variable number of pickers on the same page.
![image](https://user-images.githubusercontent.com/26480299/130004522-0783862b-8faf-405b-9b9b-a66e6550b7dd.png)

We'd like to reuse a single change handler for all the pickers because it wouldn't be feasible to have one setDate for each.
This can be accomplished by exposing the event, then we can use data attributes to know which date is changed.

**Comment by shahabyazdi** [comment]
Due to the fact that onChange can be called in different situations (when the user is clicking on the day, when the user is typing in the input) also onChange can be called by other plugins in different situations, no specific event can be considered for that.

In my opinion, there are two solutions.

Sending special event as a second argument for each of these situations (in which no event may be sent for plugins case)

Or sending the ref of DatePicker as the second argument in all cases.

Which one do you prefer, or let me know if you have another suggestion.

**Comment by henry132109** [comment]
Thank you for the prompt reply!
I think being able to retrieve the rmdp-container ref and transverse up its ancestors is good enough.

**Comment by shahabyazdi** [comment]
There is also a third way that seems more reasonable to me and I want to share with you before starting work on the previous suggestions.
And that is to wrap the datepicker in a primary component and receive the required data from it.

please check this sandbox to see what I mean:

https://codesandbox.io/s/nice-wescoff-j03ko?file=/src/App.js

**Comment by henry132109** [comment]
> There is also a third way that seems more reasonable to me and I want to share with you before starting work on the previous suggestions.
> And that is to wrap the datepicker in a primary component and receive the required data from it.
> 
> please check this sandbox to see what I mean:
> 
> https://codesandbox.io/s/nice-wescoff-j03ko?file=/src/App.js

That's definitely a more reacty way to accomplish it. Absolutely lovin' it.
