### ISSUE TITLE
Getting raw input instead of DateObject

### ISSUE THREAD

**Issue by emorevival** [shahabyazdi/react-multi-date-picker#64]
Hi, 

I'm using your `DatePicker` component to render a styled `input`, in which the user can enter text as well. I want to check the entered text so that I can validate it, but `onChange` gives me a `DateObject`, which returns null if the input is bad. Is there a way that I can get the exact string the user entered in the input field?

**Comment by shahabyazdi** [comment]
Currently, the only way to get the input value is to use a ref.

I have prepared an example for you, please check it and if the problem isn't solved in that way, let me know so that I'll work on a version that sends the input event as the second argument in the onChange method.

https://codesandbox.io/s/getting-input-value-if-date-is-null-kd4u5?file=/src/App.js

**Comment by emorevival** [comment]
Thanks! I'm actually able to get the input value this way. Is there a way to prevent the user from entering dates such as `20/20/2020` or is that outside of the scope of this component? Currently if I enter the aforementioned date, it selects August 20 2021, and I can't test it with regex either because as soon as the input is within the date format (DD/MM/YYYY), it's treated as a `DateObject`

**Comment by shahabyazdi** [comment]
Your problem is that you are validating the input value `after` it sends to the date picker.
The best thing to do for your case is to check the input value `before` it has been sent to the date picker
You can use a custom input to do this:

https://codesandbox.io/s/intelligent-firefly-pnqr3?file=/src/App.js

**Comment by emorevival** [comment]
That works like a charm, thank you! I think I can close this now, I appreciate your quick help :)
