### ISSUE TITLE
Convert unix problem

### ISSUE THREAD

**Issue by Shawnfoto** [shahabyazdi/react-multi-date-picker#9]
![螢幕快照 2020-12-25 下午6 35 54](https://user-images.githubusercontent.com/18244561/103132562-0ecf0900-46e0-11eb-9a78-e7c125d097cf.png)

I don't know why I selected date, this unix will become 2021/01/01 00:00

**Comment by shahabyazdi** [comment]
Can you give me time values ? (Hour:minute:second: millisecond)

**Comment by Shawnfoto** [comment]
![Uploading 螢幕快照 2020-12-25 下午10.07.31.png…]()

**Comment by Shawnfoto** [comment]
sometimes I got 1609430400, but sometimes is 16094303999, when I chose 12/31.

**Comment by shahabyazdi** [comment]
I suppose the problem probably is with this line of code .  
Rounding the time value adds 1 second to unix time if the millisecond value is greater than 499.

```javascript
    get unix() {
        return Math.round(this.valueOf() / 1000)
    }
```

Please give me some time to work on it.

**Comment by shahabyazdi** [comment]
Unfortunately, I did several different tests but did not encounter the problem you mentioned. 

Anyway, since it is probably due to the rounding value of time, I updated the package DateObject, but I'm not sure if the problem you mentioned has been resolved.

Please take a look [here ](https://codesandbox.io/s/unix-time-test-6dm6q)and see if it still persists or not.

cafa320aef38084c621832af547e06366be65853

**Comment by Shawnfoto** [comment]
I think it can work, thank you.

**Comment by shahabyazdi** [comment]
You're welcome
